#! /bin/sh
### BEGIN INIT INFO
# Provides:          uptimed
# Required-Start:    $remote_fs
# Required-Stop:     $remote_fs
# Should-Start:      uptimed-init
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Uptime daemon
### END INIT INFO

PATH=/sbin:/bin:/usr/sbin:/usr/bin
DAEMON=/usr/sbin/uptimed
NAME=uptimed
DESC="uptime daemon"

test -f $DAEMON || exit 0

. /lib/lsb/init-functions

case "$1" in
  start)
	echo -n "Starting $DESC: "
	start-stop-daemon --start --quiet --user daemon --chuid daemon --exec $DAEMON
	echo "$NAME."
	;;
  stop)
	echo -n "Stopping $DESC: "
	start-stop-daemon --stop --quiet --user daemon --exec $DAEMON
	echo "$NAME."
	;;
  restart|force-reload)
	echo -n "Restarting $DESC: "
	start-stop-daemon --stop --quiet --user daemon --exec $DAEMON
	sleep 1
	start-stop-daemon --start --quiet --user daemon --chuid daemon --exec $DAEMON
	echo "$NAME."
	;;
  restart-if-running)
	set +e
	echo -n "Restarting $DESC (if running): "
	if start-stop-daemon --stop --quiet --user daemon --exec $DAEMON; then
		sleep 1
		start-stop-daemon --start --quiet --user daemon --chuid daemon --exec $DAEMON
	fi
	echo "$NAME."
	;;
  status)
	status_of_proc "$DAEMON" "$NAME" && exit 0 || exit $?
	;;
  *)
	N=/etc/init.d/$NAME
	echo "Usage: $N {start|stop|restart|force-reload|status}" >&2
	exit 1
	;;
esac

exit 0
